apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - namespace: istio-system
        name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 200m
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: __cert_arn #value will be replaced when applied
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,8443,15020,15443,31400"

# apiVersion: install.istio.io/v1alpha2
# kind: IstioControlPlane
# metadata:
#   namespace: istio-operator
#   name: ingress-gateway
# spec:
#   profile: demo
#   values:
#     gateways:
#       istio-ingressgateway:
#         serviceAnnotations:
#           service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
