# bug https://github.com/istio/istio/issues/24377
# ---
# apiVersion: install.istio.io/v1alpha2
# kind: IstioOperator
# spec:
#   components:
#     ingressGateways:
#       k8s:
#         serviceAnnotations:
#           service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
---
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: ingress-gateway
spec:
  profile: demo
  values:
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:073251215989:certificate/93a3d0ba-3a07-4231-ab9b-4c5b80248668" #value will be replaced when applied
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,8443,15020,15443,31400"
