---
- name: crictl | Download crictl
  include_tasks: "../../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.crictl) }}"

- name: Install crictl config
  template:
    src: ../templates/crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: bin
    mode: 0644

- name: Copy crictl binary from download dir
  synchronize:
    src: "{{ local_release_dir }}/crictl"
    dest: "{{ bin_dir }}/crictl"
    compress: no
    perms: yes
    owner: no
    group: no
  delegate_to: "{{ inventory_hostname }}"

- name: Install crictl completion
  shell: "{{ bin_dir }}/crictl completion >/etc/bash_completion.d/crictl"
  ignore_errors: True
  when: ansible_distribution in ["CentOS","RedHat", "Ubuntu", "Debian"]
