---

molecule_tests:
  tags: [vagrant]
  only: [/^pr-.*$/]
  except: ['triggers']
  image: quay.io/miouge/kubespray-vagrant
  services: []
  stage: deploy-part1
  before_script:
    - tests/scripts/rebase.sh
    - apt-get update && apt-get install -y python3-pip
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    - python -m pip install -r tests/requirements.txt
  script:
    - ./tests/scripts/molecule_run.sh
