---
dependencies:
  - role: kubernetes-apps/external_cloud_controller/openstack
    when:
      - cloud_provider is defined
      - cloud_provider == "external"
      - external_cloud_provider is defined
      - external_cloud_provider == "openstack"
      - inventory_hostname == groups['kube-master'][0]
    tags:
      - external-cloud-controller
      - external-openstack
