---
docker_kernel_min_version: '0'

# https://docs.docker.com/install/linux/docker-ce/fedora/
# https://download.docker.com/linux/fedora/28/x86_64/stable/Packages/

docker_versioned_pkg:
  'latest': docker-ce
  '18.03': docker-ce-18.03.1.ce-3.fc28
  '18.06': docker-ce-18.06.2.ce-3.fc28
  '18.09': docker-ce-18.09.7-3.fc28

#
# This is due to the fact that the docker
# packages available on Fedora are too recent
#
docker_version: "latest"

docker_package_info:
  pkg_mgr: dnf
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
