---
- name: External OpenStack Cloud Controller | check external_openstack_auth_url value
  fail:
    msg: "external_openstack_auth_url is missing"
  when: external_openstack_auth_url is not defined or not external_openstack_auth_url

- name: External OpenStack Cloud Controller | check external_openstack_username value
  fail:
    msg: "external_openstack_username is missing"
  when: external_openstack_username is not defined or not external_openstack_username

- name: External OpenStack Cloud Controller | check external_openstack_password value
  fail:
    msg: "external_openstack_password is missing"
  when: external_openstack_password is not defined or not external_openstack_password

- name: External OpenStack Cloud Controller | check external_openstack_region value
  fail:
    msg: "external_openstack_region is missing"
  when: external_openstack_region is not defined or not external_openstack_region

- name: External OpenStack Cloud Controller | check external_openstack_tenant_id value
  fail:
    msg: "one of external_openstack_tenant_id or external_openstack_tenant_name must be specified"
  when:
    - external_openstack_tenant_id is not defined or not external_openstack_tenant_id
    - external_openstack_tenant_name is not defined

- name: External OpenStack Cloud Controller | check external_openstack_tenant_name value
  fail:
    msg: "one of external_openstack_tenant_id or external_openstack_tenant_name must be specified"
  when:
    - external_openstack_tenant_name is not defined or not external_openstack_tenant_name
    - external_openstack_tenant_id is not defined
