---
crio_rhel_repo_base_url: 'https://cbs.centos.org/repos/paas7-crio-114-candidate/x86_64/os/'

crio_seccomp_profile: "/etc/crio/seccomp.json"

crio_cgroup_manager: "{{ kubelet_cgroup_driver | default('cgroupfs') }}"

crio_runc_path: "/usr/sbin/runc"
