---

containerd_versioned_pkg:
  'latest': "{{ containerd_package }}"
  '1.2.4': "{{ containerd_package }}=1.2.4-1"
  '1.2.5': "{{ containerd_package }}=1.2.5-1"
  '1.2.6': "{{ containerd_package }}=1.2.6-3"
  '1.2.10': "{{ containerd_package }}=1.2.10-3"
  '1.2.12': "{{ containerd_package }}=1.2.12-1"
  '1.2.13': "{{ containerd_package }}=1.2.13-1"
  'stable': "{{ containerd_package }}=1.2.13-1"
  'edge': "{{ containerd_package }}=1.2.13-1"

containerd_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "{{ containerd_versioned_pkg[containerd_version | string] }}"
      force: false

containerd_repo_key_info:
  pkg_key: apt_key
  url: '{{ containerd_debian_repo_gpgkey }}'
  repo_keys:
    - '{{ containerd_debian_repo_repokey }}'

containerd_repo_info:
  pkg_repo: apt_repository
  repos:
    - >
       deb {{ containerd_debian_repo_base_url }}
       {{ ansible_distribution_release|lower }}
       {{ containerd_debian_repo_component }}

runc_binary: /usr/bin/runc
