---
- hosts: bastion[0]
  gather_facts: False
  roles:
    - { role: kubespray-defaults}
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"]}
- hosts: kube-master[0]
  tags:
    - "provision"
  roles:
    - { role: kubespray-defaults}
    - { role: provision }
