---

containerd_versioned_pkg:
  'latest': "{{ containerd_package }}"
  '1.2.4': "{{ containerd_package }}-1.2.4-3.1.el7"
  '1.2.5': "{{ containerd_package }}-1.2.5-3.1.el7"
  '1.2.6': "{{ containerd_package }}-1.2.6-3.3.el7"
  '1.2.10': "{{ containerd_package }}-1.2.10-3.2.el7"
  '1.2.12': "{{ containerd_package }}-1.2.12-3.1.el7"
  '1.2.13': "{{ containerd_package }}-1.2.13-3.1.el7"
  'stable': "{{ containerd_package }}-1.2.13-3.1.el7"
  'edge': "{{ containerd_package }}-1.2.13-3.1.el7"

containerd_package_info:
  pkg_mgr: yum
  pkgs:
    - name: "{{ containerd_versioned_pkg[containerd_version | string] }}"

containerd_pkgs:
  - name: "{{ containerd_versioned_pkg[containerd_version | string] }}"
    yum_conf: "{{ containerd_yum_conf }}"

containerd_repo_key_info:
  pkg_key: ''
  repo_keys: []

containerd_repo_info:
  pkg_repo: ''
  repos: []

runc_binary: /bin/runc
